server:
  port: ${APPLICATION_PORT:8080}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

grpc:
  server:
    port: 6566

kafka:
  topics:
    commands: commands
    queries: queries
    responses: responses