services:

  mongo:
    image: mongo:latest
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017" ]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
      - ../scripts/mongo/init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
    healthcheck:
      test: echo 'rs.status().ok' | mongosh --quiet --port 27017
      interval: 5s
      timeout: 30s
      retries: 30

volumes:
  mongo-data:
  mongo-config: